version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Node.js App from Docker Hub
  app:
    image: sraven93/ecommerce-app:latest
    container_name: ecommerce_app
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-password123}@postgres:5432/ecommerce
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      NODE_ENV: production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /app/node_modules
    command: >
      sh -c "
        echo 'Waiting for DB...' &&
        sleep 5 &&
        echo 'Running database migration and seed...' &&
        npx drizzle-kit push &&
        npx tsx scripts/seed.ts &&
        echo 'Starting Node server...' &&
        node dist/server.js
      "
    restart: unless-stopped

volumes:
  postgres
