version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # E-commerce Application
  app:
    build: .
    container_name: ecommerce_app
    environment:
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/ecommerce
      JWT_SECRET: your-super-secret-jwt-key-for-docker
      NODE_ENV: production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
        npx drizzle-kit push &&
        npx tsx scripts/seed.ts &&
        npm start
      "

volumes:
  postgres_data: